#!/usr/bin/env bash
#
# Materialises an offline, greppable copy of Bedrock's two authoritative
# documentation sources. Both are public Git repos, so we clone the source
# markdown directly instead of scraping rendered HTML.
#
# The output directory is gitignored: it is a local search corpus, not a
# build input. Re-running this script refreshes it in place.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$ROOT/reference-docs"

# Text formats only. Images, .mcpack/.mcaddon archives and .nbt binaries are
# skipped: they are the bulk of these repos and contribute nothing to search.
EXTENSIONS=(md json ts js yaml yml txt csv)

# name|url|branch|subtree
SOURCES=(
  "bedrock-wiki|https://github.com/Bedrock-OSS/bedrock-wiki|wiki|docs"
  "minecraft-creator|https://github.com/MicrosoftDocs/minecraft-creator|main|creator"
)

# Bash 3.2 ships with macOS and has no case-modifying expansions, hence tr.
keep() {
  local ext allowed
  ext="$(printf '%s' "${1##*.}" | tr '[:upper:]' '[:lower:]')"
  for allowed in "${EXTENSIONS[@]}"; do
    [[ "$ext" == "$allowed" ]] && return 0
  done
  return 1
}

prune() {
  local dir="$1" file
  while IFS= read -r file; do
    keep "$file" || rm -f "$file"
  done < <(find "$dir" -type f ! -path '*/.git/*')
  find "$dir" -type d -empty ! -name '.git' -delete 2>/dev/null || true
}

fetch_one() {
  local name="$1" url="$2" branch="$3" subtree="$4"
  local dir="$DEST/$name" patterns=()

  # Non-cone sparse takes gitignore-style globs, so we can ask for specific
  # extensions and never download the ~4.5k images these repos carry.
  for ext in "${EXTENSIONS[@]}"; do
    patterns+=("/$subtree/**/*.$ext")
  done

  # Stale files from a previous, wider pattern set are not reclaimed by
  # `sparse-checkout set` alone, so reset before re-applying.
  if [[ -d "$dir/.git" ]]; then
    echo "updating $name ($branch)"
    git -C "$dir" fetch --depth 1 origin "$branch" --quiet
    git -C "$dir" reset --hard FETCH_HEAD --quiet
    git -C "$dir" sparse-checkout set --no-cone "${patterns[@]}" >/dev/null
  else
    echo "cloning  $name ($branch)"
    git clone --depth 1 --single-branch --branch "$branch" \
      --filter=blob:none --sparse --quiet "$url" "$dir"
    git -C "$dir" sparse-checkout set --no-cone "${patterns[@]}" >/dev/null
  fi

  prune "$dir"
  echo "         $(find "$dir" -type f ! -path '*/.git/*' | wc -l | tr -d ' ') files"
}

mkdir -p "$DEST"
for entry in "${SOURCES[@]}"; do
  IFS='|' read -r name url branch subtree <<< "$entry"
  fetch_one "$name" "$url" "$branch" "$subtree"
done

# A flat index makes the corpus navigable without a search tool at hand.
INDEX="$DEST/INDEX.md"
{
  echo "# Offline Bedrock reference corpus"
  echo
  echo "Generated by \`scripts/fetch-reference-docs.sh\`. Do not edit by hand."
  echo
  echo "Search it with: \`rg --no-ignore <term> reference-docs/\`"
  echo
  for entry in "${SOURCES[@]}"; do
    IFS='|' read -r name _ _ _ <<< "$entry"
    echo "## $name"
    echo
    (cd "$DEST" && find "$name" -type f ! -path '*/.git/*' -name '*.md' | sort | sed 's/^/* /')
    echo
  done
} > "$INDEX"

echo
echo "corpus ready: $DEST"
du -sh "$DEST" 2>/dev/null || true
